# Generated by Django 5.1.6 on 2025-03-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
