# Generated by Django 5.1.6 on 2025-02-11 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atenciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('descripcion', models.TextField()),
                ('id_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atenciones.atencion')),
            ],
        ),
    ]
