# Generated by Django 5.1.6 on 2025-02-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_nombre_usuario_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Médico'), ('paciente', 'Paciente')], max_length=20),
        ),
    ]
